---
# tasks file for mheap.wordpress
# Copying already downloaded WordPress ------------------------------------#
# curl -O https://wordpress.org/latest.zip
#- name: Copy wordpress.zip into tmp
#  copy: src=wordpress.zip dest=/tmp/wordpress.zip
# Downloading it Automatically --------------------------------------------#
- name: Get WordPress checksum
  uri: url=https://wordpress.org/latest.zip.sha1 return_content=true
  register: wp_checksum
- name: Download WordPress
  get_url: 
    url: https://wordpress.org/latest.zip
    dest: /tmp/wordpress.zip
    checksum: "sha1:{{wp_checksum.content}}"
#--------------------------------------------------------------------------#
- name: installed required tools
  apt: name=unzip state=present
- name: Unzip WordPress
  unarchive: src=/tmp/wordpress.zip dest=/tmp copy=no creates=/tmp/wordpress/wp-settings.php
- name: Create project folder
  file: dest=/var/www/'{{wp_domain}}' state=directory
- name: Copy WordPress files
  command: cp -a /tmp/wordpress/. /var/www/'{{wp_domain}}' creates=/var/www/'{{wp_domain}}'/wp-settings.php
- name: Create WordPress MySQL database
  mysql_db: name="{{database_name}}" state=present
- name: Create WordPress MySQL user
  mysql_user: name="{{database_user}}" host=localhost password="{{database_password}}" priv="{{database_name}}".*:ALL
- name: Create wp-config
# cp /tmp/wordpress/wp-config.php /vagrant/provisioning/templates/
  template: src=wp-config.php dest=/var/www/'{{wp_domain}}'/wp-config.php
- name: Dose the database exist?
  command: mysql -u root "{{database_name}}" -e "SELECT ID FROM "{{database_name}}".wp_users LIMIT 1;"
  register: db_exist
  ignore_errors: true
  changed_when: false
- name: Copy WordPress DB
# mysqldump wordpress > /vagrant/provisioning/files/wp-database.sql
  template: src=wp-database.sql dest=/tmp/wp-database.sql
  when: db_exist.rc > 0
- name: Import WordPress DB
  mysql_db: target=/tmp/wp-database.sql state=import name="{{database_name}}"
  when: db_exist.rc > 0
