---
- hosts: all
  tasks:
    - name: Install Apache
      command: yum install --quiet -y httpd httpd-devel
    #- name: Copy configuration files
    #  command: >
    #    cp /path/to/config/httpd.conf /etc/httpd/conf/httpd.conf
    #- command: >
    #    cp /path/to/config/httpd-vhosts.conf /etc/httpd/conf/httpd-vhosts.conf
    - name: Start Apache and confugure it to run at boot
      command: service httpd start
    - command: chkconfig httpd on

# -- RUN --
# vagrant up
# ansible-playbook cmd-playbook.yml --become  --limit 192.168.60.4